#!/bin/sh
#PBS -N USPEX-19
#PBS -l nodes=1:ppn=4
cd $PBS_O_WORKDIR

source /etc/profile.d/intel.sh

export CUDA_VISIBLE_DEVICES=0

mpirun -np 4 /opt/vasp5/vasp.5.4.4/bin/vasp_std > output
env

mpirun -np 4 /opt/vasp5/vasp.5.4.4/bin/vasp_std > output
